name: sur-server
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/ucore-hci
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - cockpit-navigator
      - cockpit-ostree

  - type: signing 

